#!/usr/bin/env python3
"""Registers the item appearances a 15.25 client knows that the server does not.

Reads appearances.dat (protobuf) and the existing modern id table, finds every
item appearance with no server-side item, and emits:

  data/items/items_1525.toml   [[items]] entries (name, article, container type)
  appended rows in data/items/modern_client_ids.tsv  (serverId -> appearanceId)

New server ids are allocated sequentially from --first-id (default 30000,
safely above the highest assets.dat/toml id). The mapping table stays the
single source of truth for the wire translation; gameplay attributes for the
new items (weight, armor, slots) are intentionally left for hand-tuning.

Regenerating is idempotent: existing generated rows are replaced, not stacked.

Usage:
  protoc --proto_path=src/protobuf --python_out=<dir> appearances.proto
  python3 harness/build_new_items.py [--first-id 30000]
"""

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GENERATED_HEADER = "# generated by harness/build_new_items.py - new 15.25 items below"


def load_pb(pb_dir):
    sys.path.insert(0, str(pb_dir))
    import appearances_pb2 as pb  # noqa: E402
    return pb


def article_for(name):
    if not name:
        return ""
    return "an" if name[0].lower() in "aeiou" else "a"


def toml_escape(text):
    return text.replace("\\", "\\\\").replace('"', '\\"')


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--appearances", default=str(ROOT / "data/items/appearances.dat"))
    parser.add_argument("--mapping", default=str(ROOT / "data/items/modern_client_ids.tsv"))
    parser.add_argument("--out-toml", default=str(ROOT / "data/items/items_1525.toml"))
    parser.add_argument("--first-id", type=int, default=30000)
    parser.add_argument("--pb-dir", default="/tmp/pbgen")
    args = parser.parse_args()

    pb = load_pb(args.pb_dir)
    apps = pb.Appearances()
    apps.ParseFromString(Path(args.appearances).read_bytes())

    mapping_lines = []
    mapped_appearances = set()
    for line in Path(args.mapping).read_text().splitlines():
        if line.startswith(GENERATED_HEADER):
            break
        mapping_lines.append(line)
        if line.startswith("#") or not line.strip():
            continue
        fields = line.split("\t")
        if len(fields) >= 2:
            mapped_appearances.add(int(fields[1]))

    new_items = []
    next_id = args.first_id
    for obj in sorted(apps.object, key=lambda o: o.id):
        if not obj.HasField("id") or not obj.HasField("flags"):
            continue
        if obj.id in mapped_appearances:
            continue
        if next_id > 0xFFFF:
            raise SystemExit(f"ran out of u16 server ids at appearance {obj.id}")
        new_items.append((next_id, obj))
        next_id += 1

    toml_out = [
        "# New 15.25 item appearances with no 10.98-era server item.",
        "# Generated by harness/build_new_items.py - ids map through",
        "# modern_client_ids.tsv. Gameplay attributes are defaults; tune by hand.",
        "",
    ]
    for server_id, obj in new_items:
        name = obj.name.decode("utf-8", "replace") if obj.HasField("name") else ""
        toml_out.append("[[items]]")
        toml_out.append(f"id = {server_id}")
        toml_out.append(f'article = "{toml_escape(article_for(name))}"')
        toml_out.append(f'name = "{toml_escape(name)}"')
        if obj.flags.container:
            toml_out.append('type = "container"')
            toml_out.append("containersize = 8")
        toml_out.append("")
    Path(args.out_toml).write_text("\n".join(toml_out))

    mapping_lines.append(GENERATED_HEADER)
    for server_id, obj in new_items:
        name = obj.name.decode("utf-8", "replace") if obj.HasField("name") else ""
        mapping_lines.append(f"{server_id}\t{obj.id}\tgenerated\t{name}")
    Path(args.mapping).write_text("\n".join(mapping_lines) + "\n")

    named = sum(1 for _, o in new_items if o.HasField("name") and len(o.name))
    print(f"registered {len(new_items)} new items ({named} named), "
          f"server ids {args.first_id}..{next_id - 1}")


if __name__ == "__main__":
    main()
