#!/usr/bin/env python3
"""Generate data/items/modern_client_ids.tsv (server id -> modern appearance id).

Ground truth chain:
  1. TFS 10.98 items.otb maps server id -> 10.98 client id.
  2. CipSoft appearance ids are append-only across client generations, so a
     10.98 client id IS the 13.x/14.x/15.x appearance id for any object that
     existed in 10.98 (spot-verified: gold coin 3031, bag 2853, red apple
     3585, torch 2920 identical in canary's 15.25 items.xml).

The generated TSV carries a confidence column: rows whose item name in
BlackTek's items.toml matches canary's items.xml name for the mapped
appearance id are marked `name-verified`; the rest are `otb-only` (usually
fine - names drift, ids don't - but eyeball them before trusting a specific
one in content).

Usage:
  python3 build_modern_ids.py --otb ~/Documents/forgottenserver-ref/data/items/items.otb \
      --canary-items ~/Documents/canary/data/items/items.xml \
      --out ../data/items/modern_client_ids.tsv
"""

import argparse
import re
import struct
import sys
import tomllib
from pathlib import Path

NODE_START = 0xFE
NODE_END = 0xFF
ESCAPE = 0xFD

ATTR_SERVERID = 0x10
ATTR_CLIENTID = 0x11


def parse_otb(path):
    """Yield (server_id, client_id) from a TFS items.otb."""
    data = Path(path).read_bytes()
    pos = 4  # skip signature

    # walk the byte stream; we only care about item node attributes
    pairs = []
    server_id = client_id = None
    in_item = False
    depth = 0
    while pos < len(data):
        byte = data[pos]
        if byte == NODE_START:
            depth += 1
            pos += 2  # start marker + node type byte
            if depth == 2:  # item nodes live directly under the root
                if server_id is not None and client_id is not None:
                    pairs.append((server_id, client_id))
                server_id = client_id = None
                in_item = True
                pos += 4  # item flags u32
            continue
        if byte == NODE_END:
            depth -= 1
            pos += 1
            continue
        if not in_item or depth != 2:
            pos += 1
            continue

        # attribute: u8 type, u16 length, payload (with 0xFD escapes)
        attr = data[pos]
        pos += 1
        raw_len = bytearray()
        for _ in range(2):
            if data[pos] == ESCAPE:
                pos += 1
            raw_len.append(data[pos])
            pos += 1
        (length,) = struct.unpack("<H", bytes(raw_len))
        payload = bytearray()
        while len(payload) < length:
            if data[pos] == ESCAPE:
                pos += 1
            payload.append(data[pos])
            pos += 1

        if attr == ATTR_SERVERID:
            (server_id,) = struct.unpack("<H", payload[:2])
        elif attr == ATTR_CLIENTID:
            (client_id,) = struct.unpack("<H", payload[:2])

    if server_id is not None and client_id is not None:
        pairs.append((server_id, client_id))
    return pairs


def load_blacktek_names(items_toml):
    names = {}
    with open(items_toml, "rb") as f:
        data = tomllib.load(f)
    for it in data["items"]:
        name = it.get("name")
        if name is None:
            continue
        if "id" in it:
            names[it["id"]] = name.lower()
        elif "fromid" in it:
            for i in range(it["fromid"], it["toid"] + 1):
                names[i] = name.lower()
    return names


def load_canary_names(items_xml):
    text = Path(items_xml).read_text()
    names = {}
    for m in re.finditer(r'<item id="(\d+)"[^>]*name="([^"]*)"', text):
        names[int(m.group(1))] = m.group(2).lower()
    for m in re.finditer(r'<item fromid="(\d+)" toid="(\d+)"[^>]*name="([^"]*)"', text):
        for i in range(int(m.group(1)), int(m.group(2)) + 1):
            names[i] = m.group(3).lower()
    return names


def main():
    here = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser()
    parser.add_argument("--otb", required=True)
    parser.add_argument("--canary-items", required=True)
    parser.add_argument("--blacktek-items", default=str(here.parent / "data" / "items" / "items.toml"))
    parser.add_argument("--out", default=str(here.parent / "data" / "items" / "modern_client_ids.tsv"))
    args = parser.parse_args()

    pairs = parse_otb(args.otb)
    blacktek = load_blacktek_names(args.blacktek_items)
    canary = load_canary_names(args.canary_items)

    verified = 0
    written = 0
    unmapped = sorted(set(blacktek) - {sid for sid, _ in pairs})
    with open(args.out, "w") as out:
        out.write("# server_id\tappearance_id\tconfidence\tname\n")
        out.write("# generated by harness/build_modern_ids.py - see that file for the ground-truth chain\n")
        for sid, cid in sorted(pairs):
            if sid not in blacktek:
                continue  # not an item BlackTek defines
            bt_name = blacktek.get(sid, "")
            ca_name = canary.get(cid, "")
            confidence = "name-verified" if bt_name and bt_name == ca_name else "otb-only"
            verified += confidence == "name-verified"
            out.write(f"{sid}\t{cid}\t{confidence}\t{bt_name}\n")
            written += 1

    print(f"wrote {written} mappings to {args.out}")
    print(f"  name-verified: {verified} ({100*verified/max(written,1):.1f}%)")
    print(f"  BlackTek ids with no OTB mapping: {len(unmapped)} (custom/newer items)")
    if unmapped:
        print("  first unmapped:", unmapped[:15])
    return 0


if __name__ == "__main__":
    sys.exit(main())
