#!/usr/bin/env python3
"""Generate data/items/modern_client_ids.tsv (server id -> modern appearance id).

Ground truth chain:
  1. TFS 10.98 items.otb maps server id -> 10.98 client id.
  2. CipSoft appearance ids are append-only across client generations, so a
     10.98 client id IS the 13.x/14.x/15.x appearance id for any object that
     existed in 10.98 (spot-verified: gold coin 3031, bag 2853, red apple
     3585, torch 2920 identical in canary's 15.25 items.xml).

The generated TSV carries a confidence column: rows whose item name in
BlackTek's items.toml matches canary's items.xml name for the mapped
appearance id are marked `name-verified`; the rest are `otb-only` (usually
fine - names drift, ids don't - but eyeball them before trusting a specific
one in content).

Ids the legacy assets.dat describes are mapped even without an items.toml
entry: borders and decorations carry none, yet the client stacks a tile by
them, so an unmapped one shifts every stackpos above it. Those rows are only
written when appearances.dat still has the appearance (CipSoft deleted most
unnamed 10.98 objects), which keeps the loader's pruned count meaningful.

The block harness/build_new_items.py appends is kept as it is: its server ids
may already be on the map or in player items, so they are never renumbered.

Usage:
  protoc --proto_path=src/protobuf --python_out=/tmp/pbgen appearances.proto
  python3 build_modern_ids.py --otb ~/Documents/forgottenserver-ref/data/items/items.otb \
      --canary-items ~/Documents/canary/data/items/items.xml \
      --out ../data/items/modern_client_ids.tsv
"""

import argparse
import re
import struct
import sys
import tomllib
from pathlib import Path

NODE_START = 0xFE
NODE_END = 0xFF
ESCAPE = 0xFD

ATTR_SERVERID = 0x10
ATTR_CLIENTID = 0x11

GENERATED_HEADER = "# generated by harness/build_new_items.py - new 15.25 items below"


def read_dat_item_count(path):
    """The last server id the legacy assets.dat describes (u16 after the signature)."""
    (count,) = struct.unpack_from("<H", Path(path).read_bytes(), 4)
    return count


def load_appearance_ids(appearances, pb_dir):
    """Every object id in a modern client's protobuf appearances.dat."""
    sys.path.insert(0, str(pb_dir))
    import appearances_pb2 as pb  # noqa: E402
    parsed = pb.Appearances()
    parsed.ParseFromString(Path(appearances).read_bytes())
    return {obj.id for obj in parsed.object if obj.HasField("id") and obj.HasField("flags")}


def read_generated_block(path):
    """Lines from the build_new_items.py header onward, or [] without one."""
    if not Path(path).exists():
        return []
    lines = Path(path).read_text().splitlines()
    for index, line in enumerate(lines):
        if line.startswith(GENERATED_HEADER):
            return lines[index:]
    return []


def parse_otb(path):
    """Yield (server_id, client_id) from a TFS items.otb."""
    data = Path(path).read_bytes()
    pos = 4  # skip signature

    # walk the byte stream; we only care about item node attributes
    pairs = []
    server_id = client_id = None
    in_item = False
    depth = 0
    while pos < len(data):
        byte = data[pos]
        if byte == NODE_START:
            depth += 1
            pos += 2  # start marker + node type byte
            if depth == 2:  # item nodes live directly under the root
                if server_id is not None and client_id is not None:
                    pairs.append((server_id, client_id))
                server_id = client_id = None
                in_item = True
                pos += 4  # item flags u32
            continue
        if byte == NODE_END:
            depth -= 1
            pos += 1
            continue
        if not in_item or depth != 2:
            pos += 1
            continue

        # attribute: u8 type, u16 length, payload (with 0xFD escapes)
        attr = data[pos]
        pos += 1
        raw_len = bytearray()
        for _ in range(2):
            if data[pos] == ESCAPE:
                pos += 1
            raw_len.append(data[pos])
            pos += 1
        (length,) = struct.unpack("<H", bytes(raw_len))
        payload = bytearray()
        while len(payload) < length:
            if data[pos] == ESCAPE:
                pos += 1
            payload.append(data[pos])
            pos += 1

        if attr == ATTR_SERVERID:
            (server_id,) = struct.unpack("<H", payload[:2])
        elif attr == ATTR_CLIENTID:
            (client_id,) = struct.unpack("<H", payload[:2])

    if server_id is not None and client_id is not None:
        pairs.append((server_id, client_id))
    return pairs


def load_blacktek_names(items_toml):
    names = {}
    with open(items_toml, "rb") as f:
        data = tomllib.load(f)
    for it in data["items"]:
        name = it.get("name")
        if name is None:
            continue
        if "id" in it:
            names[it["id"]] = name.lower()
        elif "fromid" in it:
            for i in range(it["fromid"], it["toid"] + 1):
                names[i] = name.lower()
    return names


def load_canary_names(items_xml):
    text = Path(items_xml).read_text()
    names = {}
    for m in re.finditer(r'<item id="(\d+)"[^>]*name="([^"]*)"', text):
        names[int(m.group(1))] = m.group(2).lower()
    for m in re.finditer(r'<item fromid="(\d+)" toid="(\d+)"[^>]*name="([^"]*)"', text):
        for i in range(int(m.group(1)), int(m.group(2)) + 1):
            names[i] = m.group(3).lower()
    return names


def main():
    here = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser()
    parser.add_argument("--otb", required=True)
    parser.add_argument("--canary-items", required=True)
    parser.add_argument("--blacktek-items", default=str(here.parent / "data" / "items" / "items.toml"))
    parser.add_argument("--assets", default=str(here.parent / "data" / "items" / "assets.dat"))
    parser.add_argument("--appearances", default=str(here.parent / "data" / "items" / "appearances.dat"))
    parser.add_argument("--pb-dir", default="/tmp/pbgen")
    parser.add_argument("--out", default=str(here.parent / "data" / "items" / "modern_client_ids.tsv"))
    args = parser.parse_args()

    pairs = parse_otb(args.otb)
    blacktek = load_blacktek_names(args.blacktek_items)
    canary = load_canary_names(args.canary_items)
    dat_count = read_dat_item_count(args.assets)
    appearance_ids = load_appearance_ids(args.appearances, args.pb_dir)
    generated = read_generated_block(args.out)

    verified = 0
    written = 0
    unmapped = sorted(set(blacktek) - {sid for sid, _ in pairs})
    with open(args.out, "w") as out:
        out.write("# server_id\tappearance_id\tconfidence\tname\n")
        out.write("# generated by harness/build_modern_ids.py - see that file for the ground-truth chain\n")
        for sid, cid in sorted(pairs):
            if sid not in blacktek and (sid > dat_count or cid not in appearance_ids):
                continue  # not an item BlackTek defines, or one the client no longer has
            bt_name = blacktek.get(sid, "")
            ca_name = canary.get(cid, "")
            confidence = "name-verified" if bt_name and bt_name == ca_name else "otb-only"
            verified += confidence == "name-verified"
            out.write(f"{sid}\t{cid}\t{confidence}\t{bt_name}\n")
            written += 1
        for line in generated:
            out.write(f"{line}\n")

    print(f"wrote {written} mappings to {args.out}")
    print(f"  kept {max(len(generated) - 1, 0)} build_new_items.py rows")
    print(f"  name-verified: {verified} ({100*verified/max(written,1):.1f}%)")
    print(f"  BlackTek ids with no OTB mapping: {len(unmapped)} (custom/newer items)")
    if unmapped:
        print("  first unmapped:", unmapped[:15])
    return 0


if __name__ == "__main__":
    sys.exit(main())
