# Database connection configuration

[mysql]
host               = "127.0.0.1"
user               = "forgottenserver"
pass               = "bt_test"
database           = "blacktek"
port               = 3307
socket             = ""
optimize_on_startup = false
